# Use the official Python lightweight image
FROM python:3.13-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install the project into /app
COPY . /app
WORKDIR /app

# Allow statements and log messages to immediately appear in the logs
ENV PYTHONUNBUFFERED=1

# Install dependencies
RUN uv sync

EXPOSE 7000

# Run the FastMCP server
CMD ["uv", "run", "server.py"]

# gcloud run deploy mcp-server --allow-unauthenticated --region=us-central1 --source . --port 7000